apiVersion: v1
kind: Pod
metadata:
  name: "worker"
spec:
  containers:
  - name: worker
    image: {{ images.worker }}
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "3"
        memory: 4Gi
    env:
      - name: DOCKER_HOST
        value: localhost
    volumeMounts:
      - name: eve
        mountPath: /home/scality/eve
  - name: docker-daemon
    image: docker:18.09.7-dind
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    securityContext:
      privileged: true
    volumeMounts:
      - name: eve
        mountPath: /home/scality/eve
      - name: docker-storage
        mountPath: /var/lib/docker
  volumes:
    # The two volumes below are used to avoid intensive IO in the Docker overlay
    # If extra performance is required, one could add `medium: Memory` to the
    # `emptyDir` dicts.
    # See https://docs.docker.com/storage/volumes/
    - name: docker-storage
      emptyDir: {}
    - name: eve
      emptyDir:
        medium: Memory
